# .github/workflows/cd-azure.yml
name: CD – Deploy Docker Image to Azure

on:
  workflow_run:
    workflows: ["Build Image & Publish to Docker Hub"]
    types: [completed]
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_NAME: fgc

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy container to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.DOCKERHUB_USERNAME }}/fcg:latest
          
